(cl:defpackage drone_cable_detection-srv
  (:use )
  (:export
   "ALIGN_WITH_WIRE"
   "<ALIGN_WITH_WIRE-REQUEST>"
   "ALIGN_WITH_WIRE-REQUEST"
   "<ALIGN_WITH_WIRE-RESPONSE>"
   "ALIGN_WITH_WIRE-RESPONSE"
   "TARGET_GLOBAL_POS"
   "<TARGET_GLOBAL_POS-REQUEST>"
   "TARGET_GLOBAL_POS-REQUEST"
   "<TARGET_GLOBAL_POS-RESPONSE>"
   "TARGET_GLOBAL_POS-RESPONSE"
   "TARGET_LOCAL_POS"
   "<TARGET_LOCAL_POS-REQUEST>"
   "TARGET_LOCAL_POS-REQUEST"
   "<TARGET_LOCAL_POS-RESPONSE>"
   "TARGET_LOCAL_POS-RESPONSE"
  ))

