// Generated by gencpp from file drone_cable_detection/align_with_wireRequest.msg
// DO NOT EDIT!


#ifndef DRONE_CABLE_DETECTION_MESSAGE_ALIGN_WITH_WIREREQUEST_H
#define DRONE_CABLE_DETECTION_MESSAGE_ALIGN_WITH_WIREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_cable_detection
{
template <class ContainerAllocator>
struct align_with_wireRequest_
{
  typedef align_with_wireRequest_<ContainerAllocator> Type;

  align_with_wireRequest_()
    : timeOut(0.0)  {
    }
  align_with_wireRequest_(const ContainerAllocator& _alloc)
    : timeOut(0.0)  {
  (void)_alloc;
    }



   typedef double _timeOut_type;
  _timeOut_type timeOut;





  typedef boost::shared_ptr< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> const> ConstPtr;

}; // struct align_with_wireRequest_

typedef ::drone_cable_detection::align_with_wireRequest_<std::allocator<void> > align_with_wireRequest;

typedef boost::shared_ptr< ::drone_cable_detection::align_with_wireRequest > align_with_wireRequestPtr;
typedef boost::shared_ptr< ::drone_cable_detection::align_with_wireRequest const> align_with_wireRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator1> & lhs, const ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator2> & rhs)
{
  return lhs.timeOut == rhs.timeOut;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator1> & lhs, const ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_cable_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7a138008fb2d0c41d90d6ef0f7caaf3";
  }

  static const char* value(const ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7a138008fb2d0c4ULL;
  static const uint64_t static_value2 = 0x1d90d6ef0f7caaf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_cable_detection/align_with_wireRequest";
  }

  static const char* value(const ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 timeOut\n"
;
  }

  static const char* value(const ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeOut);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct align_with_wireRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_cable_detection::align_with_wireRequest_<ContainerAllocator>& v)
  {
    s << indent << "timeOut: ";
    Printer<double>::stream(s, indent + "  ", v.timeOut);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CABLE_DETECTION_MESSAGE_ALIGN_WITH_WIREREQUEST_H
