// Generated by gencpp from file drone_cable_detection/align_with_wire.msg
// DO NOT EDIT!


#ifndef DRONE_CABLE_DETECTION_MESSAGE_ALIGN_WITH_WIRE_H
#define DRONE_CABLE_DETECTION_MESSAGE_ALIGN_WITH_WIRE_H

#include <ros/service_traits.h>


#include <drone_cable_detection/align_with_wireRequest.h>
#include <drone_cable_detection/align_with_wireResponse.h>


namespace drone_cable_detection
{

struct align_with_wire
{

typedef align_with_wireRequest Request;
typedef align_with_wireResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct align_with_wire
} // namespace drone_cable_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drone_cable_detection::align_with_wire > {
  static const char* value()
  {
    return "cbc1dbe05903c9604fb7ff840d1f16c4";
  }

  static const char* value(const ::drone_cable_detection::align_with_wire&) { return value(); }
};

template<>
struct DataType< ::drone_cable_detection::align_with_wire > {
  static const char* value()
  {
    return "drone_cable_detection/align_with_wire";
  }

  static const char* value(const ::drone_cable_detection::align_with_wire&) { return value(); }
};


// service_traits::MD5Sum< ::drone_cable_detection::align_with_wireRequest> should match
// service_traits::MD5Sum< ::drone_cable_detection::align_with_wire >
template<>
struct MD5Sum< ::drone_cable_detection::align_with_wireRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drone_cable_detection::align_with_wire >::value();
  }
  static const char* value(const ::drone_cable_detection::align_with_wireRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_cable_detection::align_with_wireRequest> should match
// service_traits::DataType< ::drone_cable_detection::align_with_wire >
template<>
struct DataType< ::drone_cable_detection::align_with_wireRequest>
{
  static const char* value()
  {
    return DataType< ::drone_cable_detection::align_with_wire >::value();
  }
  static const char* value(const ::drone_cable_detection::align_with_wireRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drone_cable_detection::align_with_wireResponse> should match
// service_traits::MD5Sum< ::drone_cable_detection::align_with_wire >
template<>
struct MD5Sum< ::drone_cable_detection::align_with_wireResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drone_cable_detection::align_with_wire >::value();
  }
  static const char* value(const ::drone_cable_detection::align_with_wireResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_cable_detection::align_with_wireResponse> should match
// service_traits::DataType< ::drone_cable_detection::align_with_wire >
template<>
struct DataType< ::drone_cable_detection::align_with_wireResponse>
{
  static const char* value()
  {
    return DataType< ::drone_cable_detection::align_with_wire >::value();
  }
  static const char* value(const ::drone_cable_detection::align_with_wireResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONE_CABLE_DETECTION_MESSAGE_ALIGN_WITH_WIRE_H
