// Generated by gencpp from file drone_cable_detection/target_local_pos.msg
// DO NOT EDIT!


#ifndef DRONE_CABLE_DETECTION_MESSAGE_TARGET_LOCAL_POS_H
#define DRONE_CABLE_DETECTION_MESSAGE_TARGET_LOCAL_POS_H

#include <ros/service_traits.h>


#include <drone_cable_detection/target_local_posRequest.h>
#include <drone_cable_detection/target_local_posResponse.h>


namespace drone_cable_detection
{

struct target_local_pos
{

typedef target_local_posRequest Request;
typedef target_local_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct target_local_pos
} // namespace drone_cable_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drone_cable_detection::target_local_pos > {
  static const char* value()
  {
    return "fb2d2cec436c25bb2c92caf8218fe6ff";
  }

  static const char* value(const ::drone_cable_detection::target_local_pos&) { return value(); }
};

template<>
struct DataType< ::drone_cable_detection::target_local_pos > {
  static const char* value()
  {
    return "drone_cable_detection/target_local_pos";
  }

  static const char* value(const ::drone_cable_detection::target_local_pos&) { return value(); }
};


// service_traits::MD5Sum< ::drone_cable_detection::target_local_posRequest> should match
// service_traits::MD5Sum< ::drone_cable_detection::target_local_pos >
template<>
struct MD5Sum< ::drone_cable_detection::target_local_posRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drone_cable_detection::target_local_pos >::value();
  }
  static const char* value(const ::drone_cable_detection::target_local_posRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_cable_detection::target_local_posRequest> should match
// service_traits::DataType< ::drone_cable_detection::target_local_pos >
template<>
struct DataType< ::drone_cable_detection::target_local_posRequest>
{
  static const char* value()
  {
    return DataType< ::drone_cable_detection::target_local_pos >::value();
  }
  static const char* value(const ::drone_cable_detection::target_local_posRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drone_cable_detection::target_local_posResponse> should match
// service_traits::MD5Sum< ::drone_cable_detection::target_local_pos >
template<>
struct MD5Sum< ::drone_cable_detection::target_local_posResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drone_cable_detection::target_local_pos >::value();
  }
  static const char* value(const ::drone_cable_detection::target_local_posResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_cable_detection::target_local_posResponse> should match
// service_traits::DataType< ::drone_cable_detection::target_local_pos >
template<>
struct DataType< ::drone_cable_detection::target_local_posResponse>
{
  static const char* value()
  {
    return DataType< ::drone_cable_detection::target_local_pos >::value();
  }
  static const char* value(const ::drone_cable_detection::target_local_posResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONE_CABLE_DETECTION_MESSAGE_TARGET_LOCAL_POS_H
